[profile.default]
solc = "0.8.15"
ffi = true
fs_permissions = [{ access = "read", path = "./artifacts/"}]
gas_reports = ["*"]
out = "out"
optimizer_runs = 1000000
metadata = true
metadata_hash = "none"  # disable ipfs
use_literal_content = true # use source code

# Monad Configuration
eth-rpc-url="https://monad-testnet.g.alchemy.com/v2/pw_4UOF9xIy14mkrmw-1zxFeZQZm6MYx"
chain_id = 10143

# fuzz settings
[profile.default.fuzz]
runs = 256
[profile.intense.fuzz]
runs = 10_000

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
single_line_statement_blocks = "single"